ТЗ 15 feat: добавить функционал запросов
Nuuvik/java-shareit pull request #4
Opened 2023-09-05 08:57 UTC by Nuuvik

2023-09-06 11:47 UTC, kalitva requested changes

2023-09-06 11:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingDtoWithId.java
> +@EqualsAndHashCode
Нам точно нужны здесь `equals`, `hashCode` и `toString`?

2023-09-06 11:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
>  }
Вместо определения всех этих методов для фильтрации объектов можно воспользоваться `Specification`, попробуй, это используется почти везде, где есть spring data

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

2023-09-06 11:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +//    @Query("select i from Item i where i.owner.id = :ownerId order by i.id  ")
Удали коммент

2023-09-06 11:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemService.java
>      }
Хм, сложновато, нм разве нужо сетать последний и следующий букинги в это методе? метод должен выглядеть примерно так
```java
    @Override
    public List<Item> search(String text) {
        if (text.isBlank()) {
            return Collections.emptyList();
        }
        return itemRepository.search(text).stream()
            map(this.mapper::toDto)
            collect...;
    }
```

2023-09-06 11:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public List<ItemDto> getItemsDtoByRequestId(Long requestId) {
Избегай слово `dto` в методах сервисах

2023-09-06 11:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/Request.java
> +    @JsonIgnore
Почему у нас в моделе эти аннотации? Разве реквесты не преобразуется в дто прежде чем попасть в контроллер?

2023-09-06 11:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/RequestDto.java
> +@Data
Давай избегать использование `@Data`

2023-09-06 11:47 UTC, kalitva commented on src/main/resources/schema.sql
>  DROP TABLE IF EXISTS users;
Не очень хорошая идея - дропать бд при каждом запуске приложения. h2 по дефолту хранит данные в памяти, это значит, что при тестировании чтобы очистить данные достаточно перезапустить приложение. Можешь для удобства использовать `spring-boot-dev-tools`, погугли

2023-09-06 19:15 UTC, Nuuvik commented on src/main/resources/schema.sql
>  DROP TABLE IF EXISTS users;
пришлось вернуть, так как не проходили некоторые тесты

2023-09-07 16:44 UTC, kalitva approved these changes

2023-09-07 16:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/RequestServiceImpl.java
> +    private final UserService userService;
Это допустимо, но желательно не инжектить сервисы друг в друга (использовать стораджы), может быть циркулярная зависимость.

2023-09-07 16:44 UTC, kalitva commented on src/main/resources/schema.sql
>  DROP TABLE IF EXISTS users;
Пожалуйста, постарайся сделать. То что у тебя тесты не проходят не причина дропать БД

2023-09-11 11:35 UTC, merged