ТЗ 16 refactor: разобрать приложение на докер-контейнеры
Nuuvik/java-shareit pull request #5
Opened 2023-09-19 14:10 UTC by Nuuvik

2023-09-20 15:03 UTC, kalitva requested changes

2023-09-20 15:03 UTC, kalitva commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingCheck.java
> +public class BookingCheck {
Лучше `BookingCheck --> BookingValidator`

2023-09-20 15:03 UTC, kalitva commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingCheck.java
> +            throw new BadParameterException("Type booking start");
Давай писать более конкретные сообщения об ошибке, напишем что-то типа что дата бронирования не может быть null

2023-09-20 15:03 UTC, kalitva commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorResponseGateway.java
> +    String error;
private

2023-09-20 15:03 UTC, kalitva commented on gateway/src/main/java/ru/practicum/shareit/exception/GatewayExceptionController.java
> +        log.warn(e.getMessage());
Давай еще передадим исключение чтобы залогировался стэктрэйс
`log.warn(e.getMessage(), e);`

2023-09-20 15:03 UTC, kalitva commented on server/pom.xml
> +            <version>2.17.2</version>
А чем тебя не устроил `logback`, который по дефолту в спринг-буте? И, наверное, в спринг-буте следует подключать log4j через стартер

https://www.baeldung.com/spring-boot-logging#log4j2-configuration-logging

2023-09-20 15:03 UTC, kalitva commented on server/src/main/java/ru/practicum/shareit/booking/BookingRepository.java
>      boolean existsByItemIdAndBookerIdAndStatusAndEndIsBefore(@NonNull Long itemId,
Не помню, говорил тебе или нет - 

Вместо определения всех этих методов для фильтрации можно воспользоваться `Specification`, это используется почти везде, где есть spring data

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

2023-09-22 15:52 UTC, Nuuvik commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorResponseGateway.java
> +    String error;
ругался, что private/protected не может быть тут. Сделал package-private.

2023-09-22 15:56 UTC, Nuuvik commented on server/src/main/java/ru/practicum/shareit/booking/BookingRepository.java
>      boolean existsByItemIdAndBookerIdAndStatusAndEndIsBefore(@NonNull Long itemId,
Говорили, да. Попробовал сделать со Specification - все сломалось, буду выяснять что не так, а пока оставлю без нее :/

2023-09-23 11:56 UTC, kalitva approved these changes

2023-09-23 11:56 UTC, kalitva commented on gateway/pom.xml
> +            <artifactId>httpclient</artifactId>
Непринципиально, но разве `httpclient` что-то умеет такого чего не может спринговый `RestTemplate`? Плюс `httpclient` как раз вроде используется под капотом рест-темплэйта, скорее всего, эту зависимость объявлять нет необходимости

2023-09-23 11:56 UTC, kalitva commented on gateway/src/main/java/ru/practicum/shareit/booking/GatewayBookingController.java
> +            @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Начиная с 5-го спринга если имена параметра url и параметра метода совпадают, нет необходимости указывать атрибут `name` аннотации `@RequestParam`

2023-09-23 11:56 UTC, kalitva commented on gateway/src/main/java/ru/practicum/shareit/booking/user/UserClient.java
> +public class UserClient extends BaseClient {
Я бы не советовал брать за основу этот паттерн - наследование от базового клиента - на будущее, лучше просто вайрить `RestTemplate` в клиенты, это будет более гибкое и правильное решение

2023-10-04 08:38 UTC, merged